### ISSUE TITLE
Probleme instalation

### ISSUE THREAD

**Issue by ekip-94** [PluginsOCSInventory-NG/sharedFolders#4]
Bonjour,
Lorsque j'installe le plugin cela fait crash mon OCS.  J'ai "installer" manuellement le Map.pm et le Shared.conf dans le repertoire. Quand je restart apache2 cela me donne un problème proxy.

**Comment by steph78630** [comment]
Bonjour @aze789 

le post suivant pourra certainement vous aider : http://ask.ocsinventory-ng.org/8747/scheduledtasks-plugins-not-visible?show=8762#a8762

Cordialement, Stéphane

**Comment by ekip-94** [comment]
Bonjour,
J'ai regarder le liens mais cela ne m'aide pas vraiment car j'ai tjrs la même erreur :/
Celle-ci ne survient que lorsque je restart apache. Lorsque j'installe le plugin directement sur la console OCS pas de soucis.

**Comment by steph78630** [comment]
Bonjour,
vérifier la présence des fichiers Map.pm et Sharedfolders.conf dans leur dossiers respectifs (attention : leur nom est sensible à la casse)

**Comment by ekip-94** [comment]
Oui, je vient de vérifier et les fichier sont bien dans leur dossier respective.

Map.pm ( /etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/sharedFolders/Map.pm )

Sharedfolders.conf ( /etc/ocsinventory-server/plugins/Sharedfolder.conf )

**Comment by steph78630** [comment]
Pour le nom du dossier de Map.pm, pouvez-vous modifier en Sharedfolders ?

**Comment by ekip-94** [comment]
Je viens de modifier le nom du dossier et j'ai toujours le même problème :(

Le problème apparaît lorsque je met le fichier .conf dans le répertoire. Le fichier serait-il corrompu ou c'est une fausse manip de ma part ?

**Comment by ekip-94** [comment]
Problème réglé il s'agissait bien d'un problème de nom du fichier.
Merci pour ton aide :)
